#!/bin/bash
git add .
echo "What is your Commit Message?"
read commit_message
git commit -m "$commit_message"
result=$?
if [ $result -eq 0]; then
	git push
else
	echo "Commit Failed, talk to Piper"
fi
