#!/bin/bash
./3-listfiles
total 32
total 24
-rwxr-xr-x 1 996 992 16 0-current_working_directory
-rw-r--r-- 1 996 992 0 0x00-shell_basics
-rwxr-xr-x 1 996 992 15 1-listit
-rwxr-xr-x 1 996 992 21 2-bring_me_home
-rwxr-xr-x 1 996 992 26 3-listfiles
-rw-r--r-- 1 996 992 18 cd
-rw-r--r-- 1 996 992 10 README.md
