#!/usr/bin/env bash
#Highlander
trap "echo I am invincible!!" SIGTERM
function no_ctrlc()
{
	echo "I am invincible!!"
{
	trap no_ctrl SIGTERM
	while :
	do
		echo "To infinity and beyond"
		sleep 2
	done
