#!/usr/bin/env bash
#displays number using the case statement
i=1

while [ $i -le 20 ]
do
	((i++))
	case "$i" in
	5)
	echo "bad luck from China";;
	10)
	echo "bad luck from Japan";;
	18)
	echo bad luck from Italy";;
	esac
done
